<?php
    return [
        'title'  => 'Privacybeleid',
        'policy' => [
            'Welkom op https://salvemundi.nl ("Wij", "We", "Onze", "De Dienst(en)", "De Site"). Lees het privacybeleid aandachtig door voordat u De Site gebruikt.',
            '<b>Cookies</b>
De Site gebruikt cookies voor het verzamelen van analytische gegevens, zoals de duur van een bezoek en terugkerende bezoeken, en voor het bijhouden van gebruikerssessies. Als u deze cookies uitschakelt, zullen deze gegevens niet correct kunnen worden verzameld.',
            'Cookies zijn kleine tekstbestanden opgeslagen op uw computer, welke uit te lezen zijn door De Site. U heeft de volledige controle over (het gebruik van) cookies, en u kunt ze uitschakelen of verwijderen. Voor meer informatie, bezoek <a href="http://www.allaboutcookies.org/">http://www.allaboutcookies.org/</a>.',
            'Als u wenst cookies uit te schakelen, dan is dit mogelijk via de instellingen van uw webbrowser. Raadpleeg de documentatie van uw webbrowser voor meer informatie.',
            '<b>Logboeken en bezoekersstatistieken</b>
We houden bezoekersstatistieken bij middels Google Analytics. Hiervoor plaatst Google cookies op uw computer en houdt Google gegevens bij over uw bezoek aan De Site. Indien wettelijk verplicht kan Google deze informatie aan derden verschaffen. Gegevens over het gebruik van De Site, inclusief uw IP-adres, worden hierbij opgeslagen op servers van Google in de Verenigde Staten. Het <a href="https://www.google.com/intl/nl/policies/privacy/">privacybeleid van Google</a> is hierop van toepassing, evenals <a href="https://support.google.com/analytics/answer/6004245?hl=nl">het privacybeleid van Google Analytics</a>.',
            'Het is mogelijk dat internetverkeer naar De Site langs de servers van Cloudflare wordt gestuurd. Bekijk het <a href="https://www.cloudflare.com/security-policy/">privacybeleid van Cloudflare</a> voor meer informatie over hoe Cloudflare omgaat met uw gegevens.',
            '<b>Persoonsgegevens</b>
De Site vraagt bij sommige formulieren mogelijk naar een aantal persoonsgegevens. Deze persoonsgegevens zijn dan vereist om u onze Diensten te kunnen leveren. Indien van toepassing zullen er niet meer persoonsgegevens gevraagd worden dan nodig. Deze persoonsgegevens zullen nooit zonder toestemming aan derden verstrekt worden tenzij Wij hiertot verplicht worden door de uitspraak van een rechter of op grond van de Nederlandse wetgeving. Deze gegevens zullen zichtbaar zijn aan hiertot bevoegde leden van de vereniging. Het is altijd mogelijk om bij ons op te vragen welke gegevens wij van u bezitten. Neem hiervoor contact met ons op.',
            'De gegevens die wij verwerken zijn de volgende, maar niet beperkt tot: <ul><li>Naam;</li><li>Adres;</li><li>Contactgegevens;</li><li>Geboortedatum;</li><li>Overige persoonsgegevens die u heeft opgegeven waar dit optioneel is; zoals het opmerkingenveld bij diverse inschrijfformulieren of bij invulvelden waarbij het geheel vrij is om de inhoud in te vullen</li></ul>',
            'Deze gegevens worden voor de volgende doeleinden bewaard en verwerkt: <ul><li>Het bijhouden van een ledenadministratie;</li><li>Het bijhouden van diverse administraties voor commissies en evenementen, zoals het bijhouden van inschrijvingen voor het kamp of het bijhouden van inschrijvingen voor de introductieweek voor nieuwe studenten;</li><li>Om contact met onze leden op te kunnen nemen voor mededelingen betreffende de vereniging of hun lidmaatschap;</li><li>Het mogelijk maken dat leden eigen inhoud plaatsen op De Site</li></ul>',
            'Deze persoonsgegevens worden niet langer dan nodig bewaard. Bij voltooide inschrijvingen zullen deze gegevens bewaard worden totdat het lidmaatschap ten einde is gekomen en de gebruiker wenst dat zijn of haar gegevens worden verwijderd. Indien een inschrijving of betaling wordt geannuleerd zullen de gegevens bij de meeste inschrijfformulieren automatisch uit het systeem verwijderd worden. ',
            '<b>Mollie als betaaldienstverlener</b>
De Site maakt gebruik van de diensten van Mollie B.V. voor het accepteren van online betalingen. Mollie verzamelt persoonsgegevens om de verwerking van transacties te garanderen. Deze persoonsgegevens worden gedeeld met De Site voor het garanderen van een correcte werking van De Diensten, zoals het inschrijven voor evenementen aangeboden door De Site en het automatisch bevestigen van betalingen gekoppeld aan formulieren op De Site. Bij het gebruik van Mollie als dienstverlener ga je akkoord met het <a href="https://www.mollie.com/nl/privacy">privacybeleid van Mollie</a>. Hierin staat beschreven welke persoonsgegevens voor welk doeleinde worden verwerkt.',
            '<b>Rechten onder algemene verordening gegevensbescherming</b>
Volgens de algemene verordening gegevensbescherming (AVG) heeft u verschillende rechten ter betrekking tot uw gegevens die wij van u bezitten. Wilt u gebruik maken van deze rechten, neem dan contact op met info@salvemundi.nl. Voor meer informatie over deze rechten, zie de onderstaande punten.<ul><li>Het recht om geïnformeerd te worden. U heeft het recht om duidelijk informatie te verkrijgen over hoe wij met uw gegevens en rechten omgaan. Deze informatie bieden wij u momenteel aan via dit privacybeleid.</li><li>Het recht op inzage. U heeft het recht om toegang te krijgen tot uw gegevens indien wij deze verwerken. Als u wenst in te zien welke gegevens wij van u bezitten, neem dan contact met ons op via bovenstaande contactgegevens.</li><li>Het recht op correctie. Indien u gelooft dat de gegevens die wij van u bezitten onjuiste informatie bevatten, dan kan u via bovenstaande contactgegevens aan ons doorgeven welke gegevens onjuist zijn. Wij zullen deze gegevens dan corrigeren.</li><li>Het recht op verwijdering. Indien u wenst dat uw gegevens niet langer door ons verwerkt worden, kunt u via bovenstaande contactgegevens een verzoek tot verwijdering bij ons indienen. Wij zullen dan uw gegevens uit onze systemen verwijderen, met uitzondering van gegevens die nodig zijn voor het functioneren De Diensten of waar vereist per wetgeving.</li><li>Het recht op dataportabiliteit. U heeft het recht om de gegevens die wij van u bezitten aan te vragen in een machineleesbaar formaat, welke u kan overdragen naar andere organisaties. Om uw gegevens in een gestructureerd en machineleesbaar formaat aan te vragen, neem dan contact op met ons via bovenstaande contactgegevens.</li></ul>',
            '<b>Sites van Derden</b>
De Site kan links naar websites van derden bevatten. Bekijk het privacybeleid van deze sites alvorens deze te gebruiken. Dit privacybeleid is niet van toepassing op, en we hebben geen invloed op de activiteiten van, deze sites van derden.',
            '<b>Wijzigingen aan dit Privacybeleid</b>
We kunnen periodiek dit privacybeleid bijwerken. Wanneer we dat doen, zullen we ook de ingangsdatum aanpassen. Door De Site en/of De Diensten te blijven gebruiken gaat u automatisch akkoord met dit privacybeleid.',
            '<i>Ingangsdatum: 25 mei 2018</i>'
        ]
    ];